query and update animals table
Chaseknis/vet_clinic_database pull request #2
Opened 2023-03-30 15:08 UTC by Chaseknis

- update the animals table
- Create a savepoint for the transaction
- Rollback to the savepoint
- Commit transaction

 ## Screen-Shots
<img width="1680" alt="Screenshot 2023-03-30 at 16 34 19" src="https://user-images.githubusercontent.com/97366651/228881035-82a63aed-f704-4fb0-8d22-0ff8a5fd8152.png">
<img width="1680" alt="Screenshot 2023-03-30 at 16 37 26" src="https://user-images.githubusercontent.com/97366651/228881058-6f306082-d0ef-4703-bd3f-53fdf1b91c0c.png">
<img width="1680" alt="Screenshot 2023-03-30 at 16 49 17" src="https://user-images.githubusercontent.com/97366651/228881082-533dd094-191c-4863-9ea2-cd26e4e1c5c6.png">
<img width="1680" alt="Screenshot 2023-03-30 at 17 02 36" src="https://user-images.githubusercontent.com/97366651/228881109-0be04053-6c1d-4404-9bda-f814b9f055f9.png">

<img width="1680" alt="Screenshot 2023-03-31 at 09 51 15" src="https://user-images.githubusercontent.com/97366651/229060288-5a60f685-abba-4cc6-af56-27ea5d607ff7.png">

<img width="1680" alt="Screenshot 2023-03-31 at 09 48 47" src="https://user-images.githubusercontent.com/97366651/229060332-c2b7c164-0c7d-416d-8dbb-4118f2cdba9f.png">

2023-03-30 18:10 UTC, Alfredbis29 requested changes
Hi @Chaseknis, 

Good job so far, I can see that you put in a lot of energy into this :+1: 
However, there are some few issues you need to work on in order to proceed to the next project, but believe me, you are almost there. 

 ![soclose](https://user-images.githubusercontent.com/97100091/205930721-3967bc84-4b21-4cec-830a-b6844fe2b36f.gif) 

## Highlights 

- Used GitHub's 'Review changes' feature from GitHub :heavy_check_mark: 
- Wrote at least 2 comments in the review :heavy_check_mark:  
- Utilised GitHub's inline comments feature for reviews :heavy_check_mark: 

## Required Changes :recycle: 

- [x] Kindly remove  React.js in the Client Tech Stack and Express.js in the Server Tech Stack since we're not using them in the project 👇🏻

![image](https://user-images.githubusercontent.com/79058364/220674010-44428ea3-610f-4e71-b438-6cacaa4dba8f.png)

- [ ] I would also recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

- [ ] Don't forget to update your screenshots of your queries results to the pull request description. :+1: 

## Optional Suggestions

Cheers and Happy coding :clap: :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29  in your question so I can receive the notification.


#### Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-30 18:10 UTC, Alfredbis29 commented on data.sql
> +    ('Blossom', '1998-09-13', 3, true, 17, '');
- [x] Kindly, Update your date_of_birth to 10 instead of 9 :arrow_down: 

```
    INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
    VALUES ('Blossom', '1998/10/13', '3', 'true', '17.0');
```

2023-03-30 18:10 UTC, Alfredbis29 commented on queries.sql
> +GROUP BY species;
- [x] Let's make sure to understand the project requirements, :point_down: 

1. What is the average number of escape attempts per animal type of those born between 1990 and 2000? 

- You need to select all the days and months for those born between 1990 and 2000. Your code might look like this :arrow_down: 

   ```sql
      SELECT species, AVG(escape_attempts) FROM animals
      GROUP BY species
      WHERE  date_of_birth >= '1990/01/01' AND date_of_birth <= '2000/12/31';;
   
   ```
1.

2023-03-30 18:10 UTC, Alfredbis29 commented on queries.sql
> +LIMIT 1;
- [x] Same here, How many animals have never tried to escape?
- Your code might look like this.

```sql
   SELECT COUNT(*) FROM animals WHERE escape_attempts = 0;
```

2023-03-30 18:27 UTC, Chaseknis commented
Thank you @Alfredbis29 Will do!

2023-03-31 07:51 UTC, Chaseknis commented on queries.sql
> +LIMIT 1;
I have all these querries in my project but sure, let me run them again @Alfredbis29

2023-03-31 08:04 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hi there 👋🏽 , 

Great work on making the changes requested by a previous reviewer 👏 
To highlight 👍🏽 
✔️ Queries are added
✔️ README is updated

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/VJNT5NYAmZiFEH6FLV/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 08:04 UTC, Ghiftee commented on data.sql
> +    ('Blossom', '1998-09-13', 3, true, 17, '');
@Chaseknis Kindly work on this as the previous reviewer mentioned.

2023-03-31 08:14 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Chaseknis, 

To highlight 👍🏽 
✔️ README is professional
✔️ Data is accurate

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 08:15 UTC, Chaseknis commented
thank you @Ghiftee

2023-03-31 08:15 UTC, merged